# Generated by Django 4.2.7 on 2024-02-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipant', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
